version: '3.8'

services:
  integration-gateway:
    build: .
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - ERP_BASE_URL=http://erp-service:8081
      - WAREHOUSE_BASE_URL=http://warehouse-service:8082
    # secrets:
    #   - jwt_secret
    depends_on:
      - erp-service
      - warehouse-service

  erp-service:
    image: node:18-alpine
    working_dir: /app
    command: sh -c "npm install -g http-server && http-server -p 8081"
    ports:
      - "8081:8081"

  warehouse-service:
    image: node:18-alpine
    working_dir: /app
    command: sh -c "npm install -g http-server && http-server -p 8082"
    ports:
      - "8082:8082"

  # secrets:
  # jwt_secret:
  #   file: ./secrets/jwt_secret.txt